name: Check





on:
  push:
  schedule:
    - cron: '0 11 * * *'





jobs:

  build:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '18' ]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install --no-save --no-fund
        env:
          ADBLOCK: true
          DISABLE_OPENCOLLECTIVE: true

      - run: npm run lint

