name: Publish





on:
  push:
    tags:
      - v/*





jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/



      - run: npm install --no-save --no-update-notifier --ignore-scripts
        env:
          ADBLOCK: true
          DISABLE_OPENCOLLECTIVE: true
          HUSKY_SKIP_INSTALL: true



      - name: Build
        run: |-
          npm run build-commonjs
          sed -i 's|"module"|"commonjs"|' package.json



      - run: npm publish --tag=next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

